Feature/shown posts
DMendybaeva/RSS-aggregator pull request #7
Opened 2022-11-15 09:36 UTC by DMendybaeva

2022-11-15 09:54 UTC, reznikovAndrey requested changes

2022-11-15 09:54 UTC, reznikovAndrey commented on src/app.js
> +  elements.modal.addEventListener('show.bs.modal', (e) => {
деструктуризация с кастомным именем
`{ relatedTarget: { dataset : { id: btnId } } }` - здесь `btnId` - кастомное имя

2022-11-15 09:54 UTC, reznikovAndrey commented on src/view/renderModalWindow.js
> +/* eslint-disable no-param-reassign */
уберем в названии файла `Window`, оставим `renderModal`

2022-11-15 09:54 UTC, reznikovAndrey commented on src/app.js
> +    watchedState.uiState.shownPosts = [activePost, ...watchedState.uiState.shownPosts];
лучше добавляй в конец, так будет быстрее с точки зрения оптимизации. 
Когда мы добавляем элемент в начало массива - нам приходится проходиться по всему массиву и сдвигать каждый элемент на 1 индекс вправо.

2022-11-15 09:54 UTC, reznikovAndrey commented on src/view/renderModalWindow.js
> +  const activePost = value[0];
здесь будем брать последний элемент. 
используй https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/at  - это новый метод у массивов, используй его с индексом -1

2022-11-15 09:54 UTC, reznikovAndrey commented on src/view/renderPosts.js
> +      const isPostShown = shownPosts.map(({ id }) => id).includes(post.id);
переименуй в `wasPostShown`. 
`post.id` сделай как `postId`, для этого сделай деструктуризацию на 18 строке
`forEach(({ id: postId, title }))`

2022-11-15 10:04 UTC, reznikovAndrey commented on src/app.js
> +      shownPosts: [],
будем использовать вместо массива `Set`, чтобы избежать дублирования

2022-11-15 10:10 UTC, reznikovAndrey commented on src/app.js
> +      shownPosts: [],
Давай использовать `Map` вместо массива, где в качестве ключа мы будем использовать `id` поста, а в качестве значения - сам пост целиком. 

Это позволит избежать дублирования и добавит в оптимизации

2022-11-15 10:31 UTC, reznikovAndrey requested changes

2022-11-15 10:31 UTC, reznikovAndrey commented on src/app.js
> +      shownPosts: [],
добавим в `uiState` еще одно свойство: `activePostId`

2022-11-15 10:31 UTC, reznikovAndrey commented on src/app.js
> +      shownPosts: [],
В качестве `shownPosts` будем использовать `Map`, где в качестве ключа будет айдишник поста, а в качестве значения - весь пост
https://learn.javascript.ru/map-set#map

2022-11-15 10:31 UTC, reznikovAndrey commented on src/app.js
> +    watchedState.uiState.shownPosts = [activePost, ...watchedState.uiState.shownPosts];
Здесь будем обновлять `activePostId` и потом добавлять в нашу коллекцию пост
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set

2022-11-15 10:31 UTC, reznikovAndrey commented on src/view/view.js
> +      renderModalWindow(value, elements);
в функцию прокидывай `state`

2022-11-15 10:31 UTC, reznikovAndrey commented on src/view/renderModalWindow.js
> +  const activePost = value[0];
Айдишник активного поста берешься из стейта. 
Дальше используешь метод 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get

2022-11-15 16:24 UTC, DMendybaeva commented on src/app.js
> +      shownPosts: [],
Использовала вместо Map, Set

2022-11-15 16:26 UTC, DMendybaeva commented on src/app.js
> +    watchedState.uiState.shownPosts = [activePost, ...watchedState.uiState.shownPosts];
Сделала shownPostsId и activePost

2022-11-15 16:37 UTC, DMendybaeva commented on src/app.js
> +      shownPosts: [],
Добавила activePost и заменила shownPosts на shownPostsId

2022-11-15 19:25 UTC, reznikovAndrey commented on src/app.js
> +      shownPostsId: new Set(),
`shownPosts` делаем массивом

2022-11-15 19:25 UTC, reznikovAndrey commented on src/app.js
> +      activePost: null,
удаляем

2022-11-15 19:26 UTC, reznikovAndrey commented on src/app.js
> +    postsButtons: document.querySelectorAll('button[data-bs-toggle="modal"]'),
это не нужно, можно удалить

2022-11-15 19:27 UTC, reznikovAndrey commented on src/app.js
> +    watchedState.uiState.activePost = activePost;
не нужно

2022-11-16 09:25 UTC, reznikovAndrey requested changes

2022-11-16 09:25 UTC, reznikovAndrey commented on src/app.js
> +    postsButtons: document.querySelectorAll('button[data-bs-toggle="modal"]'),
это нигде не используется, значит можем убрать

2022-11-16 09:25 UTC, reznikovAndrey commented on src/app.js
> +    const activePost = watchedState.posts.find(({ id }) => id === target.dataset.id);
Если мы не нашли активный пост, то получим `undefined`
это нужно предусмотреть, чтобы не сыпались ошибки в консоль

2022-11-16 09:25 UTC, reznikovAndrey commented on src/view/hideShownPosts.js
> +export default (state, elements) => {
смени название файла на `renderShownPost`

2022-11-16 09:25 UTC, reznikovAndrey commented on src/view/renderModal.js
> +  linkPost: actLinkPost,
здесь не нужны кастомные переменные, подойдут дефолтные

2022-11-16 09:25 UTC, reznikovAndrey commented on src/view/view.js
>    }
давай переименуем этот файл в `index.js`

2022-11-16 11:50 UTC, reznikovAndrey approved these changes

2022-11-16 11:50 UTC, merged